#!/bin/bash

set -e

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

arg=${1:-restart}

bucket="s3://clojars-deployment-artifacts"
releases=/home/clojars/releases
work_dir=/tmp/deploy
rm -rf $work_dir
mkdir -p $work_dir
cd $work_dir

aws s3 cp "${bucket}/current-release.txt" .
version=$(cat "${work_dir}/current-release.txt")

aws s3 cp "${bucket}/clojars-${version}.zip" .
unzip -q "clojars-${version}.zip"
mv "clojars-web-${version}-standalone.jar" $releases
cp -f scripts/* /home/clojars/bin
chmod +x /home/clojars/bin/*

ln -sf "${releases}/clojars-web-${version}-standalone.jar" "${releases}/clojars-web-current.jar"

SENTRY_TOKEN=$(aws ssm get-parameter --name "/clojars/production/sentry_token" --with-decryption --query "Parameter.Value" | tr -d '"')

curl -H "Authorization: Bearer ${SENTRY_TOKEN}" -H "Content-Type: application/json" -X POST -d "{\"version\":\"${version}\",\"ref\":\"${DEPLOY_USER}\"}" "https://app.getsentry.com/api/0/projects/clojars/clojars-web/releases/"

set +x

if [ "$arg" != "--disable-restart" ]; then
  # the clojars user only has sudo rights to run this single command
  # see /etc/sudoers.d/clojars_sudoers
  sudo systemctl restart clojars
fi

"$dir/ensure-index"
"$dir/migrate-db"
