#!/bin/bash

INDEX_DIR="/home/clojars/data/index/"

if [ -z "$(ls -A $INDEX_DIR)" ]; then
  echo "Downloading index backup..."
  aws s3 cp --no-progress "s3://clojars-artifact-index/artifact-index.tgz" /tmp/artifact-index.tgz

  echo "Extracting index backup..."
  cd /home/clojars/
  tar xzf /tmp/artifact-index.tgz
fi
