#!/bin/bash
# Useful for manual stat regeneration for a particular date
set -e

FILE=$1
DATE=$2 #$(date --date='1 day ago' +%Y%m%d)
cat $FILE | java -cp releases/clojars-web-current.jar clojure.main -m clojars.tools.process-stats > data/stats/downloads-$DATE.edn
java -cp releases/clojars-web-current.jar clojure.main -m clojars.tools.merge-stats data/stats/all.edn data/stats/downloads-$DATE.edn > /tmp/all.edn
mv /tmp/all.edn data/stats/all.edn