#!/bin/bash
set -e

cd /home/clojars/repo
find . -name '*.pom' | grep -v '/\.' | sort > all-poms.txt.new
cat all-poms.txt.new | gzip > all-poms.txt.gz.new
python /home/clojars/bin/list_artifacts.py < all-poms.txt.new | uniq | tee all-jars.clj.new | gzip > all-jars.clj.gz.new

mkdir -p ../tmp
java -cp ../releases/clojars-web-current.jar clojure.main -m clojars.tools.generate-feed /home/clojars/repo ../tmp 2> /dev/null

mv all-poms.txt.new all-poms.txt
mv all-poms.txt.gz.new all-poms.txt.gz
mv all-jars.clj.new all-jars.clj
mv all-jars.clj.gz.new all-jars.clj.gz

mv ../tmp/feed.clj.gz .
md5sum feed.clj.gz > feed.clj.gz.md5.new
mv feed.clj.gz.md5{.new,}
sha1sum feed.clj.gz > feed.clj.gz.sha1.new
mv feed.clj.gz.sha1{.new,}
