#!/bin/bash

if [ -z "$1" ]; then
  echo "Usage: $0 tag"
  echo "Or:    $0 tag yeller-api-key"
  exit 1
fi

set -e

RELEASES=/home/clojars/releases # set this with ansible?
TAG=$1
YELLER_API_KEY=$2

if [ -z "$SUDO_USER" ]; then # TODO: check this
	DEPLOY_USER=$SUDO_USER
else
	DEPLOY_USER=$USER
fi

ln -sf $RELEASES/clojars-web-"$TAG"-standalone.jar $RELEASES/clojars-web-current.jar

# TODO: check if api key was passed and uncomment
#curl -X POST "https://api.yellerapp.com/$YELLER_API_KEY/deploys?user=$DEPLOY_USER&revision=$TAG"

set +x
# echo
# echo "Okay.  Restarting the backup instance."
# sudo restart clojars-backup
# echo
# echo "Right, now do any manual testing you want on: http://clojars.org:8002/"
# echo
# echo "Once you're satisfied restart the production instance with: sudo restart clojars"

# echo "Restart the production instance with: sudo restart clojars"